# Generated by Django 4.0.5 on 2022-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('generation', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('evolution_stage', models.IntegerField()),
            ],
        ),
    ]
